/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-02-13 07:57:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pbook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>User Home Page</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\" integrity=\"sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS\" crossorigin=\"anonymous\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=css/pbook.css>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/angular.min.js\"></script>\r\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js\" integrity=\"sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js\" integrity=\"sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/contact.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div data-ng-app=\"PbookApp\" data-ng-controller=\"PbookController\" data-ng-init=\"init();\">\r\n");
      out.write("<div class=\"topnav\" id=\"con_grp_nav\">\r\n");
      out.write("  <a class={{contactActive}} data-ng-click=\"onContacts();\" data-ng-model=\"mcontact\" data-ng-value=\"contacts\">Contacts</a>\r\n");
      out.write("  <a class={{groupActive}}  data-ng-click=\"onGroups();\" data-ng-model=\"mgroup\" data-ng-value=\"groups\">Groups</a>\r\n");
      out.write("  <!-- <a style=\"float:right\" href=\"#news\"  onclick=\"msg()\" data-ng-click=\"logingout();\">Add {{addVal}}</a> -->\r\n");
      out.write("  <a  style=\"float:right\"  href=\"logout\" >LogOut</a>\r\n");
      out.write(" </div>\r\n");
      out.write(" <h1 class=\"alert alert-danger\" role=\"alert\" data-ng-hide=\"errorcontact\">{{errorAddingContact}}\r\n");
      out.write("</h1>\r\n");
      out.write(" \r\n");
      out.write(" <div data-ng-model=\"availableContacts\" data-ng-hide=\"allContacts\">\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card w-50\" data-ng-repeat=\"availContact in availableContacts | orderBy : 'contact_name'\" >\r\n");
      out.write("  <div class=\"card-body\" data-ng-init=\"initContacts(availContact.contact_id);\">\r\n");
      out.write("    <h3 class=\"card-title\">{{availContact.contact_name}}</h3>\r\n");
      out.write("    <h5 class=\"card-text\">{{availContact.ph_num_primary}}\r\n");
      out.write("     <!--  <a style=\"float:right\" href=\"#\" class=\"btn btn-primary\">...</a> -->\r\n");
      out.write("     <button  style=\"float:right\" data-ng-click=\"toggleDrop($index);\" class=\"dropbtn\">...</button>\r\n");
      out.write("     </h5>\r\n");
      out.write("     <div class=\"cdropdown\" style=\"float:right\">\r\n");
      out.write("  <div id=\"myDropdown\" class=\"cdropdown-content\" data-ng-hide=\"contactKeyArray[$index].value\">\r\n");
      out.write("    <a data-ng-click=\"deleteContact($index);\">Delete Contact</a>\r\n");
      out.write("    <!-- <a data-ng-click=\"addContactToGroup($index);\">Add To Group</a> type=\"button\" class=\"btn btn-primary\"-->\r\n");
      out.write("    <a data-ng-click=\"addContactToGroup($index);\"  data-toggle=\"modal\" data-target=\"#exampleModalLong1\">\r\n");
      out.write("  Add To Group\r\n");
      out.write("</a>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModalLong1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\">Groups Available</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      <form data-ng-submit=\"addingAContactToGroup();\" method=\"post\">\r\n");
      out.write("      <div data-ng-model=\"availableGroups\" data-ng-hide=\"hidegroups\">\r\n");
      out.write("       <div data-ng-repeat=\"availGroup in availableGroups | orderBy : 'group_name'\">\r\n");
      out.write("    <div data-ng-init=\"initConGroups(availGroup.group_id);\">\r\n");
      out.write("   \r\n");
      out.write("       <input type=\"checkbox\" data-ng-model=\"contactgroupKey[$index].value\" data-ng-checked=\"contactgroupKey[$index].value\" />{{availGroup.group_name}} <br />\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"button\" data-ng-click=\"addingAContactToGroup();\" data-dismiss=\"modal\" type=\"submit\" value=\"submit\" class=\"btn btn-primary\">Done</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <div data-ng-model=\"availableGroups\" data-ng-hide=\"allGroups\">\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"card w-50\" data-ng-repeat=\"availGroup in availableGroups | orderBy : 'group_name'\" >\r\n");
      out.write("  <div class=\"card-body\" data-ng-init=\"initGroups(availGroup.group_id);\">\r\n");
      out.write("    <h3 class=\"card-title\">{{availGroup.group_name}}</h3>\r\n");
      out.write("    <h5 class=\"card-text\">{{availGroup.user_id}}\r\n");
      out.write("     <!--  <a style=\"float:right\" href=\"#\" class=\"btn btn-primary\">...</a> -->\r\n");
      out.write("     <button  style=\"float:right\" data-ng-click=\"toggleGroupsDrop($index);\" class=\"dropbtn\">...</button>\r\n");
      out.write("     </h5>\r\n");
      out.write("     <div class=\"cdropdown\" style=\"float:right\">\r\n");
      out.write("  <div id=\"myDropdown\" class=\"cdropdown-content container\" data-ng-hide=\"groupKeyArray[$index].value\">\r\n");
      out.write("    <a data-ng-click=\"deleteGroup($index);\">Delete Group</a>\r\n");
      out.write("    <!--  <a data-ng-click=\"addContactToGroup($index);\"  data-toggle=\"modal\" data-target=\"#exampleModalLong1\"> -->\r\n");
      out.write("    <a data-ng-click=\"viewContactsInGrp($index);\" data-toggle=\"modal\" data-target=\"#exampleModalLong2\">Contacts</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModalLong2\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\">Contacts In Group</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      <form data-ng-submit=\"addingAContactToGroup();\" method=\"post\">\r\n");
      out.write("       <div data-ng-repeat=\"cingrp in coninGrps | orderBy : 'contact_name'\">\r\n");
      out.write("   <!--  <div data-ng-init=\"initConGroups(availGroup.group_id);\"> -->\r\n");
      out.write("   \r\n");
      out.write("   <h1>{{cingrp.contact_name}} :: {{cingrp.ph_num_primary}}</h1><br />\r\n");
      out.write("      <!--  <input type=\"checkbox\" data-ng-model=\"contactgroupKey[$index].value\" data-ng-checked=\"contactgroupKey[$index].value\" />{{availGroup.group_name}} <br /> -->\r\n");
      out.write("   <!--  </div> -->\r\n");
      out.write("    </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      <!--   <button type=\"button\" data-ng-click=\"addingAContactToGroup();\" data-dismiss=\"modal\" type=\"submit\" value=\"submit\" class=\"btn btn-primary\">Done</button> -->\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write(" <button class=\"open-button\" id=\"mydd\" data-ng-click=\"formOpen(addVal);\"  >Add {{addVal}}</button>\r\n");
      out.write("<div class=\"form-popup\" id=\"myForm\" data-ng-hide=\"myForm\" data-ng-model=\"myForm\">\r\n");
      out.write("  <form data-ng-submit=\"add_new_contact();\" method=\"post\" class=\"popup-form-container\">\r\n");
      out.write("    <h1>Add Contact</h1>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"name\"><b>Name</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Name\" name=\"conName\"  data-ng-model=\"contact.conName\" required>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"num1\"><b>Number</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Phone Number\" name=\"numPrimary\" data-ng-model=\"contact.numPrimary\" required>\r\n");
      out.write("    <label for=\"num2\"><b>Number</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Phone Number\" name=\"numSecondary\" data-ng-model=\"contact.numSecondary\">\r\n");
      out.write("\t<label for=\"num3\"><b>Number</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Phone Number\" name=\"numAdditional\" data-ng-model=\"contact.numAdditional\">\r\n");
      out.write("    \r\n");
      out.write("\t<label for=\"email\"><b>Email</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Email\" name=\"conEmail\" data-ng-model=\"contact.conEmail\" >\r\n");
      out.write("\t<label for=\"bday\"><b>BirthDay</b></label>\r\n");
      out.write("    <input type=\"date\" placeholder=\"Enter Name\" name=\"conDob\" data-ng-model=\"contact.conDob\" >\r\n");
      out.write("    <button type=\"submit\" value=\"submit\" class=\"btn\">Done</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn cancel\" data-ng-click=\"closeForm();\">Cancel</button>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("<div class=\"form-popup\" id=\"myCForm\" data-ng-hide=\"myCForm\" data-ng-model=\"myCForm\">\r\n");
      out.write("  <form data-ng-submit=\"add_new_group();\" method=\"post\" class=\"popup-group-form-container\">\r\n");
      out.write("    <h1>Add Group</h1>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"grpname\"><b>Group Name</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Group Name\" data-ng-model=\"group.groupName\" name=\"groupName\" required>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"submit\" value=\"submit\" class=\"btn\">Done</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn cancel\" data-ng-click=\"closeCForm();\">Cancel</button>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
